apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-apps
spec:
  replicas:1
  selector:
    mathcLabels:
      app: k8s
  template:
    metadata:
      labels:
        app: k8s
    spec:
      containers:
        - name: k8s
          image: ashok2102/portfolio:v1
          ports:
            - containerPort: 80