pipeline {
  agent any

  environment {
    AWS_REGION = 'ap-south-1'
    AWS_ACCOUNT_ID = '098588167308'
    CLUSTER_NAME = 'devops-eks-cluster'
    ECR_REPO_NAME = 'static-nginx'
  }

  stages {
    stage('Checkout Code') {
      steps {
        checkout scm
      }
    }

    stage('Terraform Destroy Infra') {
      steps {
        dir('../') {  // Go to the root folder with main.tf
          withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws_credentials']]) {
            sh 'terraform init -reconfigure'
            sh 'terraform destroy -auto-approve'
          }
        }
      }
    }
  }

  post {
    always {
      echo 'Terraform Destroy Job completed!'
    }
  }
}
