pipeline {
  agent any

  environment {
    AWS_REGION = 'ap-south-1'
  }

  stages {
    stage('Terraform Destroy Infra') {
      steps {
        dir('tf-jk-k8s') {
          sh 'terraform init'
          sh 'terraform destroy -auto-approve'
        }
      }
    }
  }
}
