pipeline {
  agent any

  environment {
    AWS_REGION = 'ap-south-1'
    AWS_ACCOUNT_ID = '098588167308'
    CLUSTER = 'devops-eks-cluster'
  }

  stages {
    stage('Terraform Destroy') {
      steps {
        withCredentials([[
          $class: 'AmazonWebServicesCredentialsBinding',
          credentialsId: 'aws_credentials'
        ]]) {
          // 👇 This tells Jenkins to go to the parent directory
          dir('../') {
            sh 'terraform init -reconfigure'
            sh 'terraform destroy -auto-approve'
          }
        }
      }
    }
  }

  post {
    always {
      echo 'Terraform Destroy Job completed!'
    }
  }
}
